# Generated by Django 6.0.5 on 2026-05-17 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('categoria', models.CharField(choices=[('software', 'Problema de Software / Bug'), ('hardware', 'Problema de Hardware'), ('acesso', 'Acessos e Permissões'), ('financeiro', 'Financeiro e Faturamento'), ('outros', 'Outros Assuntos')], default='software', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('atendimento', 'Em Atendimento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_criados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
